<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<UseWPF>true</UseWPF>
		<LangVersion>Latest</LangVersion>
		<PlatformTarget>x64</PlatformTarget>
		<ApplicationIcon>label.ico</ApplicationIcon>

		<Title>SOReplaceLabel</Title>
		<Product>SOReplaceLabel</Product>
		<Version>1.3.1.0</Version>
		<NeutralLanguage>ja-JP</NeutralLanguage>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<RunCodeAnalysis>true</RunCodeAnalysis>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="label.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Wada.SOReplaceLabel.Application\Wada.SOReplaceLabel.Application.csproj" />
		<ProjectReference Include="..\WpfMVVM\WpfMvvm.csproj" />
		<ProjectReference Include="..\SOReplaceUpdater\SOReplaceUpdater.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MahApps.Metro" Version="2.4.11" />
		<PackageReference Include="MaterialDesignColors" Version="5.2.1" />
		<PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
		<PackageReference Include="MaterialDesignThemes.MahApps" Version="5.2.1" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="WindowsAPICodePack-Core" Version="1.1.2" />
		<PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
	</ItemGroup>

	<Target Name="CopyUpdater" AfterTargets="Build">
		<Copy SourceFiles="$(SolutionDir)SOReplaceUpdater\bin\$(Configuration)\net48\SOReplaceUpdater.exe" DestinationFolder="$(OutputPath)" ContinueOnError="true" />
	</Target>

	<ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>
</Project>
